### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by jbiams77** [MultipedRobotics/pyservos#4]
The following lines in the __init__.py file throw this issue:
```
try:
    from importlib_metadata import version # type: ignore
except ImportError:
    from importlib.metadata import version # type: ignore
```

It seems related to issue: [1487](https://github.com/python-poetry/poetry/issues/1487)

Poetry version 1.0.0b3
Python 3.7.3
Raspberry Pi 4
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:          10
Codename:     buster

**Comment by walchko** [comment]
So this seems to work fine on my Ubuntu desktop system, but I haven't tried it on a raspberry pi in a while. I will look into it.

**Comment by walchko** [comment]
I think it is a small issue based on the differences between my system and yours. I made some changes to the `toml` and the `__init__.py`. If I am right, then it is subtle issue you found :smile:. Let me know if it is fixed for you.
